### ISSUE TITLE
p77 这句话怎么理解？

### ISSUE THREAD

**Issue by Littlesqx** [MiYogurt/nodejs-shizhan#12]
p77 3.4.1 第二个段落

> 而且把大对象加入全局对象上会发生内存泄漏，需要谨慎而行。

为何内存泄漏受这个影响？内存泄漏不是因为程序不严谨或者 GC 没做好吗？

**Comment by MiYogurt** [comment]
容易泄露，有的时候，你动态添加点东西进去，一不小心忘记清理了就很泄露了。
