### ISSUE TITLE
为啥删了设计章节

### ISSUE THREAD

**Issue by YuYang019** [MiYogurt/nodejs-shizhan#2]
刚刚入手，没有设计章节看的真的没头没尾的。。。对于整个应用读者不知道整体架构，即使一块块代码告诉我这个是什么功能，也读的很云里雾里啊。。抓不到重点。这本书的介绍不就是以实现一个类Dribble应用为核心吗，全书不是应该围绕这个主题的来叙述吗，然后穿插一些原理工具之类的。。没了这些章节，我身为一个读者的感受就是没头没尾，代码太多不知所云。。

对于一些不知道这个章节被删了的读者，可能就弃书了，读起来感觉真的不太好。。要不是我在cnode社区里看到您的评论说这些章节被删了，还真不知道

最后，感谢您的付出，以上是身为读者的一点感受，不当之处请见谅

**Comment by MiYogurt** [comment]
图片太多了，书的页数会变多，而且主题是Node.js，穿插设计，编辑觉得不太合适。

扫描二维码，在微信公众号就可以获得被删除的章节。
