### ISSUE TITLE
第55页创建 user 的 migration 失败

### ISSUE THREAD

**Issue by Kerminate** [MiYogurt/nodejs-shizhan#4]
![image](https://user-images.githubusercontent.com/26789139/46254780-4467f600-c4c7-11e8-8219-ea461d6a14dc.png)

**Comment by Kerminate** [comment]
原因是缺少 attributes 参数
![image](https://user-images.githubusercontent.com/26789139/46254987-54cda000-c4ca-11e8-9b14-87484375946a.png)

**Comment by MiYogurt** [comment]
attributes 可以手动自己写的。

**Comment by wershest** [comment]
对于一些读者会产生误导，（比如我，一直使用mongodb），毕竟不是所有的读者都具备 “所有的” 背景知识。 作为一个程序员，我自然的会认为，书中的每一行代码和命令都是可以执行的。
