### ISSUE TITLE
关于mysql时区问题，插入中文字段数据库报错

### ISSUE THREAD

**Issue by Jackliu007888** [MiYogurt/nodejs-shizhan#8]
# 时区问题
因为时区原因，默认存储的 type 是 Date，比如 created_at，updated_at 总是跟实际差八小时。
排除docker安装 mysql 有时区问题后，
最后发现要在 sequelize 的配置项中加 timezone: '+08:00'

```js
// config.default.js
config.sequelize = {
    dialect: 'mysql',
    database: 'XX',
    host: 'XXXXX',
    port: 'XX',
    username: 'XX',
    password: 'XX',
    timezone: '+08:00'
  }
```

# 插入中文字段数据库报错
默认是 latin 1,不支持中文，
改mysql的编码为 utf-8解决，请问如何在创建表的时候修改默认编码呢？

# 关于字段增删 如何修改 sequelize
另外请教，如果mysql已经建表了，发现字段需要增加，是在migrations目录中新建一个js，然后执行 npx sequelize db:migrate 吗？
还是要先回退版本？

书中关于 sequelize 的教程偏少，看了你推荐的视频教程是付费的，暂无打算付费。

以上

**Comment by MiYogurt** [comment]
migration 的 queryInterface 有 API 对表做修改，建立索引，删除字段，添加字段等等。自行查找 API 即可。

mysql 的 conf 文件可以修改默认编码。

已创建可以手动修改，使用图形化界面更改会简单些，也可以通过命令

```
ALTER TABLE `test`.`table_user` CHANGE COLUMN `username` `username` VARCHAR(45) CHARACTER SET 'utf8_unicode_ci' NOT NULL ;
```
